### ISSUE TITLE
Suggestions + some hints

### ISSUE THREAD

**Issue by aaghamohammadi** [phosseini/COVID19-fa#3]
Hello @phosseini 

It is an interesting work. I have found informative information in your paper. For example, In Figure 4 and Topic 45, you see topics such as ```virus``` and ```Khamenei```. I think this topic appears since some of the regime oppositions use the hashtag ```Khameneivirus```. I don't see this hashtag in your tags file. Maybe it's a good idea to check it and find another topic.

One more thing, I did a  similar task (of course in another concept). You can check out our paper at [arxiv](https://arxiv.org/pdf/2004.06280.pdf). We also used a temporal trend analysis. It enabled us to find more knowledge about the task we had studied. In my opinion, a similar temporal trend analysis could improve your work.

Best wishes

**Comment by phosseini** [comment]
@aaghamohammadi good points, thanks for your feedback. 

I'll add the tag to our list for future analysis. It seems like the tag is associated mostly with tweets in English. On the temporal trend analysis, totally agree, we're doing some analysis for different time bins to see how conversations evolved over time.

**Comment by aaghamohammadi** [comment]
To get attention from the media, they try to write tweets in English. I don't know what proportion of their tweets are in English. Probably you need to do some heuristics to get a clear view of this hashtag.
